import pathlib
import subprocess
import sys
import typing as t

import tomllib

"""
`uv pip compile` generates `requirements.txt` based on `pyproject.toml` and (tautologically) `requirements.txt`.
`uv export` doesn't include index urls.

This script generates a `requirements.txt` file containing the index urls specified in `pyproject.toml`.
It's the best of both worlds.

Ref: https://github.com/astral-sh/uv/issues/15394
"""


class IndexEntry(t.NamedTuple):
    name: str
    url: str
    default: bool


def read_index_urls() -> list[IndexEntry]:
    with open("pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    indexes = data.get("tool", {}).get("uv", {}).get("index", [])
    return [
        IndexEntry(
            name=idx["name"],
            url=idx["url"],
            default=bool(idx.get("default", False)),
        )
        for idx in indexes
    ]


def format_index_lines(indexes: list[IndexEntry]) -> list[str]:
    lines: list[str] = []
    default_emitted = False
    if indexes:
        script_path = pathlib.Path(__file__).resolve().relative_to(pathlib.Path.cwd())
        lines.append(
            f"# The following index urls were autogenerated from pyproject.toml by {script_path.as_posix()}"
        )
        for idx in indexes:
            lines.append(f"# {idx.name}")
            if idx.default and not default_emitted:
                lines.append(f"--index-url {idx.url}")
                default_emitted = True
            else:
                lines.append(f"--extra-index-url {idx.url}")
    return lines


def run_uv_export() -> str:
    result = subprocess.run(
        ["uv", "export", "--format", "requirements.txt", "--no-default-groups", "--no-hashes"],
        check=True,
        capture_output=True,
        text=True,
    )

    return result.stdout


def main() -> int:
    indexes = read_index_urls()
    index_lines = format_index_lines(indexes)
    export_output = run_uv_export()

    sys.stdout.write("\n".join(index_lines))
    if index_lines:
        sys.stdout.write("\n\n")
    sys.stdout.write(export_output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
